import type { Metadata } from "next";
import { LegalShell } from "@/components/legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Brainura collects, uses, and protects your personal information.",
};

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" updated="May 25, 2026">
      <p>
        This Privacy Policy explains how Brainura (&quot;Brainura&quot;,
        &quot;we&quot;, &quot;us&quot;, &quot;our&quot;) collects, uses, shares,
        and protects personal information when you use our mobile application
        and related services (collectively, the &quot;Service&quot;). We
        designed Brainura with privacy in mind: we collect only what we need to
        run the product, we never sell your data, and we do not display
        third-party advertising.
      </p>

      <h2>1. Who is responsible for your data</h2>
      <p>
        The data controller is Hanna Kravchenko, the developer of Brainura,
        based in Ukraine. For any privacy-related question or to exercise the
        rights described in this policy you can reach us at{" "}
        <a href="mailto:krv4art.dev@gmail.com">krv4art.dev@gmail.com</a>.
      </p>

      <h2>2. Data we collect</h2>

      <h3>2.1 Information you provide</h3>
      <ul>
        <li>
          <strong>Account information</strong> &mdash; if you sign in, we store
          your email address and the display name you choose. Sign-in is
          optional; the app can be used anonymously.
        </li>
        <li>
          <strong>Onboarding answers</strong> &mdash; goals, focus areas, age
          group, and preferences you select during onboarding so we can
          personalise your training programme.
        </li>
        <li>
          <strong>Support messages</strong> &mdash; if you write to us, we keep
          the conversation so we can follow up.
        </li>
      </ul>

      <h3>2.2 Information generated by your use of the Service</h3>
      <ul>
        <li>
          <strong>Exercise results</strong> &mdash; scores, accuracy, duration,
          per-exercise details, streaks and Brain Age estimates.
        </li>
        <li>
          <strong>App interactions</strong> &mdash; which screens you visit,
          which features you use, and basic preferences (language, theme).
        </li>
        <li>
          <strong>Device and diagnostic data</strong> &mdash; device model, OS
          version, app version, locale, time zone, anonymised crash logs and
          performance metrics.
        </li>
        <li>
          <strong>Approximate location</strong> &mdash; derived from your IP
          address at the country/city level for regional content and analytics.
          We do <strong>not</strong> request or use precise GPS data.
        </li>
        <li>
          <strong>Identifiers</strong> &mdash; an anonymous Supabase user ID, a
          OneSignal player ID for notifications, and Apple/Google purchase
          identifiers. None of these can be used to identify you outside of
          Brainura.
        </li>
        <li>
          <strong>Purchase data</strong> &mdash; subscription status,
          transaction receipts and renewal information returned by Apple App
          Store, Google Play and RevenueCat.
        </li>
      </ul>

      <h2>3. How we use this data</h2>
      <ul>
        <li>To provide and personalise the training experience.</li>
        <li>To track your progress and estimate your Brain Age.</li>
        <li>To deliver push notifications you have explicitly opted in to.</li>
        <li>To detect, investigate and fix crashes and performance problems.</li>
        <li>To process subscriptions and prevent fraudulent purchases.</li>
        <li>To respond to support requests.</li>
        <li>To comply with applicable law and enforce our terms.</li>
      </ul>

      <h2>4. Legal basis (EEA/UK users)</h2>
      <p>We rely on the following legal bases under the GDPR:</p>
      <ul>
        <li>
          <strong>Contract performance</strong> &mdash; running the Service you
          requested (exercise scoring, subscription management).
        </li>
        <li>
          <strong>Legitimate interest</strong> &mdash; improving the product,
          security, anonymised analytics, and fraud prevention.
        </li>
        <li>
          <strong>Consent</strong> &mdash; push notifications, optional account
          creation, and any feature requiring an explicit opt-in.
        </li>
        <li>
          <strong>Legal obligation</strong> &mdash; tax records related to
          purchases, responding to lawful requests.
        </li>
      </ul>

      <h2>5. Sharing with third parties</h2>
      <p>
        We share data only with the processors below, each under a written data
        protection agreement. We do not sell data and we do not share it for
        third-party advertising.
      </p>
      <ul>
        <li>
          <strong>Apple App Store / Google Play</strong> &mdash; payment
          processing for in-app subscriptions.
        </li>
        <li>
          <strong>RevenueCat</strong> &mdash; subscription state management
          across stores.
        </li>
        <li>
          <strong>Supabase</strong> &mdash; database hosting and authentication.
        </li>
        <li>
          <strong>Firebase</strong> (Google LLC) &mdash; anonymised crash
          reporting, performance metrics, remote configuration.
        </li>
        <li>
          <strong>OneSignal</strong> &mdash; push notification delivery.
        </li>
        <li>
          <strong>Groq</strong> &mdash; AI inference for the optional in-app
          support chat. Your support messages are sent to Groq only when you
          use that feature.
        </li>
      </ul>

      <h2>6. Advertising and tracking</h2>
      <p>
        Brainura does <strong>not</strong> display third-party advertisements,
        does <strong>not</strong> use the iOS App Tracking Transparency
        framework, and does <strong>not</strong> share any data with
        advertising networks or data brokers. We perform first-party analytics
        only.
      </p>

      <h2>7. Data retention</h2>
      <p>
        We keep your data while your account is active and for as long as
        needed to provide the Service. After deletion, anonymised aggregate
        statistics may be retained indefinitely for product improvement; they
        cannot be linked back to you. Crash logs are deleted after 90 days.
        Purchase records are retained for the period required by tax law
        (typically up to 7 years).
      </p>

      <h2>8. Your rights</h2>
      <p>
        Depending on where you live (EEA, UK, California, and several other
        jurisdictions) you have some or all of the following rights:
      </p>
      <ul>
        <li>Access the personal data we hold about you.</li>
        <li>Request correction of inaccurate data.</li>
        <li>Request deletion (&quot;right to be forgotten&quot;).</li>
        <li>Object to or restrict certain processing.</li>
        <li>Receive your data in a portable, machine-readable format.</li>
        <li>Withdraw consent for any processing based on consent.</li>
        <li>
          Lodge a complaint with your local data protection authority. For EU
          residents you may also contact your national DPA directly.
        </li>
      </ul>
      <p>
        To exercise any of these rights, email us at{" "}
        <a href="mailto:krv4art.dev@gmail.com">krv4art.dev@gmail.com</a>. We
        respond within 30 days.
      </p>

      <h2>9. International transfers</h2>
      <p>
        Our processors operate servers in the United States and the European
        Union. When data is transferred outside the EEA, we rely on Standard
        Contractual Clauses approved by the European Commission to ensure an
        adequate level of protection.
      </p>

      <h2>10. Children</h2>
      <p>
        Brainura is rated 4+ on the App Store but is designed for adult users.
        We do not knowingly collect personal information from children under 13
        (or under 16 in the EEA) without verifiable parental consent. If you
        believe a child has provided us with personal information, contact{" "}
        <a href="mailto:krv4art.dev@gmail.com">krv4art.dev@gmail.com</a> and we
        will delete it.
      </p>

      <h2>11. Security</h2>
      <p>
        We protect your data with industry-standard measures: encryption in
        transit (HTTPS/TLS), encryption at rest, principle-of-least-privilege
        access controls, and routine security reviews. No system is perfectly
        secure; in the unlikely event of a breach affecting your personal data
        we will notify you within 72 hours where required by law.
      </p>

      <h2>12. Cookies and similar technologies</h2>
      <p>
        The Brainura mobile app does not use HTTP cookies. The marketing
        website at brainura.app uses only the technical cookies set by Vercel
        for hosting (load balancing, security). We do not use analytics
        cookies, advertising cookies, or any cross-site tracking on the
        website.
      </p>

      <h2>13. Changes to this policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Material changes
        will be announced inside the app and at the top of this page at least
        14 days before they take effect. The &quot;Last updated&quot; date at
        the top of this page reflects the latest revision.
      </p>

      <h2>14. Contact</h2>
      <p>
        For any privacy question, data request, or complaint, please email{" "}
        <a href="mailto:krv4art.dev@gmail.com">krv4art.dev@gmail.com</a>. We
        aim to reply within one business day.
      </p>
    </LegalShell>
  );
}
